// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/2f47c75835b837777a85287611703d683b0aaa83/github-electron/electron-prebuilt.d.ts
// Type definitions for electron-prebuilt 0.30.1
// Project: https://github.com/mafintosh/electron-prebuilt
// Definitions by: rhysd <https://github.com/rhysd>
// Definitions: https://github.com/borisyankov/DefinitelyTyped

declare module 'electron-prebuilt' {
	var electron: string;
	export = electron;
}